import Image from "next/image"; import Link from "next/link"; import {ArrowUpRight} from "lucide-react"; import {photos} from "@/data/site"; import {ButtonLink,SectionHead} from "@/components/ui"; import {Reveal} from "@/components/Reveal"; import {ServiceList} from "@/components/ServiceList"; import {FindCut} from "@/components/FindCut"; import {CompareSlider} from "@/components/CompareSlider"; import {CrewAccordion} from "@/components/CrewAccordion"; import {LookbookGrid} from "@/components/LookbookGrid"; import OpenStatus from "@/components/OpenStatus"; import {siteConfig} from "@/config/site";
const proofs=['4.9 customer rating','1,200+ completed cuts','Student-friendly pricing','Same-day slots','Walk-ins when available','Four specialist barbers'];
export default function Home(){return <>
<section className="grid min-h-[calc(100svh-72px)] grid-cols-[minmax(0,1fr)] border-b border-black lg:grid-cols-[46%_38%_16%]"><div className="flex min-w-0 flex-col border-b border-black p-5 lg:border-b-0 lg:border-r"><div className="meta flex justify-between gap-3"><span>CUT/CTRL — Edition 01</span><span>London / 2026</span></div><h1 className="display my-auto text-[4.55rem] leading-[.72] sm:text-[clamp(5.5rem,11vw,12rem)]">Your cut.<br/><span className="blue">Your signal.</span></h1><p className="max-w-sm text-xl">Precision for the way you move. Modern cuts, built around your face, hair and routine.</p><div className="mt-6 flex flex-wrap gap-3"><ButtonLink href="/book" className="bg-[var(--blue)] text-white">Book an appointment</ButtonLink><ButtonLink href="/cuts">Explore cuts</ButtonLink></div><div className="mt-6 grid grid-cols-2 border-t border-black pt-3"><OpenStatus className="meta"/><span className="meta">Shoreditch, LDN<br/>65 Redchurch St.</span></div></div><Reveal className="relative min-h-[65vh] min-w-0 overflow-hidden border-b border-black lg:border-b-0 lg:border-r"><Image src={photos[0]} alt="Textured modern fade at CUT/CTRL" fill priority sizes="(max-width:1024px) 100vw,38vw" className="object-cover"/></Reveal><div className="grid min-w-0 grid-rows-[1fr_auto] bg-black text-white"><div className="relative min-h-80 overflow-hidden"><Image src={photos[3]} alt="Close detail of a precision fade" fill sizes="(max-width:1024px) 100vw,16vw" className="object-cover grayscale"/></div><div className="border-t border-white/40 p-4"><p className="display text-2xl">Sharp lines.<br/>Clean finish.<br/><span className="blue">Built to last.</span></p><ArrowUpRight className="mt-8 ml-auto size-10"/></div></div></section>
<div className="overflow-hidden border-b border-black bg-[var(--paper)]"><div className="marquee-track flex">{[...proofs,...proofs].map((p,i)=><span key={i} className="display flex min-h-16 items-center border-r border-black px-8 text-xl"><i className="mr-5 text-[var(--blue)]">✳</i>{p}</span>)}</div></div>
<Reveal className="section"><SectionHead number="01" title="Signature cuts" aside="One preview. Eight directions. All built with intent."/><ServiceList/></Reveal>
<Reveal className="section border-t border-black"><SectionHead number="02" title="Find your cut" aside="Four choices. One practical recommendation."/><FindCut/></Reveal>
<Reveal className="section border-t border-black"><SectionHead number="03" title="Before / after" aside="Drag the line. Inspect the difference."/><CompareSlider/></Reveal>
<Reveal className="section border-t border-black"><SectionHead number="04" title="Crew / the four" aside="Four specialists. Choose the energy that fits."/><CrewAccordion/><div className="mt-5 text-right"><ButtonLink href="/crew">Meet the crew</ButtonLink></div></Reveal>
<Reveal className="section border-t border-black"><SectionHead number="05" title="Recent work" aside="Cut references saved from the studio floor."/><LookbookGrid preview/><div className="mt-5 text-right"><ButtonLink href="/lookbook">View full lookbook</ButtonLink></div></Reveal>
<section className="section border-t border-black"><SectionHead number="06" title="Proof, not promises" aside="Recent words from people in the chair."/><div className="grid gap-px border border-black bg-black md:grid-cols-4">{[['Nadia R.','★★★★★','Jay / Skin Fade','The detail is wild. Still sits right three weeks later.'],['Omar K.','★★★★★','Marco / Restyle','Listened first, then made the reference work for me.'],['Cal M.','★★★★★','Liam / Classic','Zero rush. Clean result. Easy conversation.'],['Sam T.','★★★★★','Zen / Beard Reset','Best beard shape I’ve had. No over-selling.']].map((r,i)=><blockquote key={r[0]} className={`bg-[var(--paper)] p-5 transition hover:-translate-y-1 hover:bg-white ${i===1?'md:row-span-2 md:min-h-72':''}`}><div className="blue">{r[1]}</div><p className="my-8 text-xl">“{r[3]}”</p><footer><b>{r[0]}</b><br/><span className="meta">{r[2]} / Recent visit</span></footer></blockquote>)}</div></section>
<section className="relative overflow-hidden bg-black px-5 py-16 text-white md:px-12 md:py-24"><div className="pointer-events-none absolute right-[8%] top-[10%] size-32 border border-[var(--blue)] opacity-60"/><OpenStatus className="meta text-[var(--blue)]" inverse/><h2 className="display max-w-5xl text-[clamp(5rem,14vw,13rem)] leading-[.76]">Don’t leave it too long.</h2><div className="mt-10 grid gap-5 border-t border-white/40 pt-5 md:grid-cols-4"><p className="meta">Starting from<br/><b className="display text-4xl">£24</b></p><p className="meta">Walk-ins<br/><b className="display text-4xl">Yes.</b></p><p className="meta">Call instead<br/><a className="text-lg hover:text-[var(--blue)]" href={`tel:${siteConfig.phone.href}`}>{siteConfig.phone.display}</a></p><Link href="/book" className="group flex items-center justify-between bg-[var(--blue)] p-5 text-xl font-bold uppercase">Book now<ArrowUpRight className="arrow"/></Link></div></section>
</>}
